version: "3.9"

services:
  web:
    build: .
    command: gunicorn rishat_test_task.wsgi:application --bind 0.0.0.0:8000 --reload
    entrypoint: /code/backend_entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: